import type { Metadata } from 'next';

import { Inter } from 'next/font/google';

import './globals.css';

import StyledComponentsRegistry from '@/lib/styledComponentRegistry';

import MSWComponent from './_components/MSWComponent';
import AuthSession from './_components/AuthSession';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StyledComponentsRegistry>
        <MSWComponent />
        <body className={inter.className}>
          <AuthSession>{children}</AuthSession>
        </body>
      </StyledComponentsRegistry>
    </html>
  );
}
